### ISSUE TITLE
Tags do not default to last value entered

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Diaries#56]
On Operation War Diary:

Input fields for 'Location', 'Unit Activity' and 'Other Unit' tags should default to the last value entered when a new tag is placed.

However, they now default to values entered many tags previously, which makes the tagging process less efficient as users are required to change details which would otherwise be common to tags on the same page.

Can we make the tags default to the last value entered?

**Comment by eatyourgreens** [comment]
Hi Darren,

I've been following this discussion on Talk. Those tags do default to the last value entered. I'm not sure how to reproduce the bug (it works properly when I try tagging pages.) I'm not sure what to suggest. Tag values are stored in the browser's local storage, so clearing the cache might fix it if something has become corrupted in the browser cache.

**Comment by eatyourgreens** [comment]
Talk discussion about this bug: http://talk.operationwardiary.org/#/boards/BWD000000m/discussions/DWD0000q22?page=2&comment_id=54c59d6129a6f63dd80005fd

**Comment by eatyourgreens** [comment]
Added a view, at #debug, to debug local storage: 488752a1d2b9d440611c3457968df4907d9fabc0

**Comment by eatyourgreens** [comment]
Hopefully fixed by flushing the stored geocoding data 43d317bad59f3ccf7b654b9511414f4e9f404f45
