### ISSUE TITLE
Google Maps API issue

### ISSUE THREAD

**Issue by ral104** [zooniverse/Diaries#57]
Attempts to tag places results in the following google maps error: invalidkeyorunauthorisedurlmaperror

This seems to affect many users, using a variety of browsers.

**Comment by eatyourgreens** [comment]
Not sure what's going on here. That's the key supplied in #38, which should give unlimited usage of Google Maps.

In the meantime, I've generated a new, free key but those are limited to 25,000 requests/day. Should be enough to hold OWD over.
