### ISSUE TITLE
Date tag: incomplete dates not stored correctly in browser

### ISSUE THREAD

**Issue by ral104** [zooniverse/Diaries#59]
Where users have placed an incomplete date tag (for example, they only have the day and month and have deleted the year) this is not stored correctly if they close down the classify page and return to it later. The date seems to revert to whatever is the earliest available date for that diary.

Affects Chrome and Firefox users. IE not yet tested.

**Comment by eatyourgreens** [comment]
Here's a screenshot from Chrome where I've entered "2 March" as a date and it saves (and displays) correctly.

![image](https://cloud.githubusercontent.com/assets/59547/12674042/93e4e102-c678-11e5-88c0-19fbf7d26607.png)

Reloading the page, the dates on the tags revert to '1 Aug 1914' so something funny is happening when the dates are saving to local storage.

**Comment by eatyourgreens** [comment]
Checking this further: choosing a date from the calendar widget sets a value that is saved when the page is reloaded, so local storage is somehow being bypassed when you type directly into the text box.

**Comment by eatyourgreens** [comment]
Fix deployed to the live site now @ral104 Have there been any problems with blank or incorrect dates showing up in the collected tag data?

**Comment by ral104** [comment]
@eatyourgreens Thanks, Jim. It's working fine for me now. I haven't noticed any bad date data so far, but I'll test a few of pages we know users had problems on.
